const drivers = [
  {
    type: 'mysql',
    name: 'MySQL',
    category: '关系型',
    family: 'mysql',
    status: 'tested',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 3306,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 3306 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'postgres',
    name: 'PostgreSQL',
    category: '关系型',
    family: 'pg',
    status: 'tested',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 5432,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 5432 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'sqlserver',
    name: 'SQL Server',
    category: '关系型',
    family: 'mssql',
    status: 'tested',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 1433,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 1433 },
      { name: 'database', label: '数据库名', type: 'text', required: true, default: 'master' },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'mariadb',
    name: 'MariaDB',
    category: '关系型',
    family: 'mysql',
    status: 'tested',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 3306,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 3306 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'tidb',
    name: 'TiDB',
    category: '关系型·国产',
    family: 'mysql',
    status: 'tested',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 4000,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 4000 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: false },
    ],
  },
  {
    type: 'clickhouse',
    name: 'ClickHouse',
    category: '分析型',
    family: 'clickhouse',
    status: 'tested',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 8123,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 8123 },
      { name: 'database', label: '数据库名', type: 'text', required: true, default: 'default' },
      { name: 'user', label: '用户名', type: 'text', required: true, default: 'default' },
      { name: 'password', label: '密码', type: 'password', required: false },
    ],
  },
  {
    type: 'elasticsearch',
    name: 'Elasticsearch',
    category: '其他',
    family: 'es-rest',
    status: 'tested',
    capabilities: { test: true, browse: true, dataset: false },
    defaultPort: 9200,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 9200 },
      { name: 'user', label: '用户名', type: 'text', required: false },
      { name: 'password', label: '密码', type: 'password', required: false },
    ],
  },
  {
    type: 'api',
    name: 'API/Web Service',
    category: '其他',
    family: 'http',
    status: 'tested',
    capabilities: { test: true, browse: false, dataset: false },
    defaultPort: null,
    fields: [
      { name: 'url', label: '接口地址', type: 'text', required: true },
      { name: 'method', label: '请求方式', type: 'select', required: true, options: ['GET', 'POST'], default: 'GET' },
      { name: 'headers', label: '请求头 (JSON)', type: 'text', required: false, default: '{}' },
      { name: 'expectedStatus', label: '期望状态码', type: 'number', required: false, default: 200 },
    ],
  },
  {
    type: 'doris',
    name: 'Apache Doris',
    category: '分析型',
    family: 'mysql',
    status: 'compatible',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 9030,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 9030 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'starrocks',
    name: 'StarRocks',
    category: '分析型',
    family: 'mysql',
    status: 'compatible',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 9030,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 9030 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'greenplum',
    name: 'Greenplum',
    category: '关系型',
    family: 'pg',
    status: 'compatible',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 5432,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 5432 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'kingbase',
    name: '人大金仓 KingbaseES',
    category: '关系型·国产',
    family: 'pg',
    status: 'compatible',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 54321,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 54321 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'gaussdb',
    name: 'GaussDB',
    category: '国产',
    family: 'pg',
    status: 'compatible',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 5432,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 5432 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'redshift',
    name: 'Amazon Redshift',
    category: '其他',
    family: 'pg',
    status: 'compatible',
    capabilities: { test: true, browse: true, dataset: true },
    defaultPort: 5439,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 5439 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'oracle',
    name: 'Oracle',
    category: '关系型',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: 1521,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 1521 },
      { name: 'service_name', label: '服务名 ServiceName', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'db2',
    name: 'DB2',
    category: '关系型',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: 50000,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 50000 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'dameng',
    name: '达梦 DM',
    category: '国产',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: 5236,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 5236 },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'gbase',
    name: '南大通用 GBASE',
    category: '国产',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: 5258,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 5258 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
      { name: 'user', label: '用户名', type: 'text', required: true },
      { name: 'password', label: '密码', type: 'password', required: true },
    ],
  },
  {
    type: 'hive',
    name: 'Apache Hive',
    category: '分析型',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: 10000,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 10000 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
    ],
  },
  {
    type: 'impala',
    name: 'Apache Impala',
    category: '分析型',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: 21050,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 21050 },
      { name: 'database', label: '数据库名', type: 'text', required: true },
    ],
  },
  {
    type: 'presto',
    name: 'Presto',
    category: '分析型',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: 8080,
    fields: [
      { name: 'host', label: '主机地址', type: 'text', required: true },
      { name: 'port', label: '端口', type: 'number', required: true, default: 8080 },
      { name: 'catalog', label: 'Catalog 目录', type: 'text', required: true },
      { name: 'schema', label: 'Schema 模式', type: 'text', required: true },
    ],
  },
  {
    type: 'maxcompute',
    name: '阿里云 MaxCompute',
    category: '其他',
    family: 'none',
    status: 'planned',
    capabilities: { test: false, browse: false, dataset: false },
    defaultPort: null,
    fields: [
      { name: 'endpoint', label: 'Endpoint 接入点', type: 'text', required: true },
      { name: 'access_key_id', label: 'AccessKey ID', type: 'text', required: true },
      { name: 'access_key_secret', label: 'AccessKey Secret', type: 'password', required: true },
      { name: 'project', label: 'Project 项目名', type: 'text', required: true },
    ],
  },
];

module.exports = drivers;