// test/helpers/store-live.js
// 构造各方言应用存储 driver；确保目标库存在；等待容器可达。
const { createSqliteDriver } = require('../../src/db/drivers/sqlite');
const { createMysqlDriver } = require('../../src/db/drivers/mysql');
const { createPostgresDriver } = require('../../src/db/drivers/postgres');
const { createMssqlDriver, parseMssqlUrl } = require('../../src/db/drivers/mssql');
const { createOracleDriver } = require('../../src/db/drivers/oracle');

const DB = 'live_store_test';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// 各方言一张含自增主键的最小表（sv_meta）DDL
function svMetaTableSql(name) {
  switch (name) {
    case 'sqlite': return 'CREATE TABLE sv_meta (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)';
    case 'mysql': return 'CREATE TABLE sv_meta (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255))';
    case 'postgres': return 'CREATE TABLE sv_meta (id BIGSERIAL PRIMARY KEY, name TEXT)';
    case 'mssql': return 'CREATE TABLE sv_meta (id BIGINT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(255))';
    case 'oracle': return 'CREATE TABLE sv_meta (id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(4000))';
    default: throw new Error(`unknown case ${name}`);
  }
}

function pingSql(name) {
  return name === 'oracle' ? 'SELECT 1 FROM DUAL' : 'SELECT 1';
}

async function ensureDatabase(cs) {
  if (cs.name === 'sqlite' || cs.name === 'oracle') return;
  if (cs.name === 'mysql') {
    const mysql2 = require('mysql2/promise');
    const conn = await mysql2.createConnection({ uri: cs.url.replace(`/${DB}`, '/testdb') });
    try { await conn.query(`CREATE DATABASE IF NOT EXISTS ${DB}`); }
    finally { await conn.end(); }
  } else if (cs.name === 'postgres') {
    const { Client } = require('pg');
    const base = new URL(cs.url);
    base.pathname = '/postgres';
    const client = new Client({ connectionString: base.toString() });
    await client.connect();
    try { await client.query(`CREATE DATABASE ${DB}`); }
    catch (e) { if (!String(e.message).toLowerCase().includes('already exists')) throw e; }
    finally { await client.end(); }
  } else if (cs.name === 'mssql') {
    const sql = require('mssql');
    const cfg = parseMssqlUrl(cs.url);
    cfg.database = 'master';
    const pool = new sql.ConnectionPool(cfg);
    await pool.connect();
    try { await pool.request().batch(`IF DB_ID(N'${DB}') IS NULL CREATE DATABASE ${DB}`); }
    finally { await pool.close(); }
  }
}

function makeStore(cs) {
  switch (cs.name) {
    case 'sqlite': return createSqliteDriver(cs.url);
    case 'mysql': return createMysqlDriver(cs.url, 'mysql');
    case 'postgres': return createPostgresDriver(cs.url);
    case 'mssql': return createMssqlDriver(cs.url);
    case 'oracle': return createOracleDriver(cs.url);
    default: throw new Error(`unknown case ${cs.name}`);
  }
}

async function createStoreFor(cs) {
  await ensureDatabase(cs);
  const store = makeStore(cs);
  const timeoutMs = 60000;
  const start = Date.now();
  let lastErr;
  while (Date.now() - start < timeoutMs) {
    try { await store.exec(pingSql(cs.name)); return store; }
    catch (e) { lastErr = e; await sleep(2000); }
  }
  throw new Error(`${cs.name} store 不可达: ${lastErr && lastErr.message}（容器是否已启动？）`);
}

module.exports = { createStoreFor, svMetaTableSql, DB };