// 按需引入 ECharts 6.x，减小打包体积
import * as echarts from 'echarts/core'
import {
  BarChart,
  LineChart,
  PieChart,
  ScatterChart,
  GaugeChart,
  FunnelChart,
  RadarChart,
  BoxplotChart,
  CandlestickChart,
  HeatmapChart,
  TreemapChart,
  SankeyChart,
  MapChart,
  GraphChart,
  PictorialBarChart,
  CustomChart,
  SunburstChart,
  ChordChart,
} from 'echarts/charts'
import {
  TitleComponent,
  TooltipComponent,
  GridComponent,
  LegendComponent,
  VisualMapComponent,
  GeoComponent,
  DatasetComponent,
  TransformComponent,
  ToolboxComponent,
  DataZoomComponent,
  MarkLineComponent,
  MarkPointComponent,
  MarkAreaComponent,
  GraphicComponent,
  CalendarComponent,
  PolarComponent,
  AriaComponent,
} from 'echarts/components'
import { LabelLayout, UniversalTransition } from 'echarts/features'
import { CanvasRenderer } from 'echarts/renderers'
import 'echarts/i18n/langZH'

echarts.use([
  BarChart,
  LineChart,
  PieChart,
  ScatterChart,
  GaugeChart,
  FunnelChart,
  RadarChart,
  BoxplotChart,
  CandlestickChart,
  HeatmapChart,
  TreemapChart,
  SankeyChart,
  MapChart,
  GraphChart,
  PictorialBarChart,
  CustomChart,
  SunburstChart,
  ChordChart,
  TitleComponent,
  TooltipComponent,
  GridComponent,
  LegendComponent,
  VisualMapComponent,
  GeoComponent,
  DatasetComponent,
  TransformComponent,
  ToolboxComponent,
  DataZoomComponent,
  MarkLineComponent,
  MarkPointComponent,
  MarkAreaComponent,
  GraphicComponent,
  CalendarComponent,
  PolarComponent,
  AriaComponent,
  LabelLayout,
  UniversalTransition,
  CanvasRenderer,
])

export default echarts
