module.exports = [
  `CREATE TABLE "datasets" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR2(255) NOT NULL,
    "original_file" VARCHAR2(255) NOT NULL, "row_count" NUMBER(10) NOT NULL DEFAULT 0,
    "column_count" NUMBER(10) NOT NULL DEFAULT 0, "table_name" VARCHAR2(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP, "source_type" VARCHAR2(20) NOT NULL DEFAULT 'excel',
    "datasource_id" NUMBER(19), "schema_name" VARCHAR2(255), "table_name_ext" VARCHAR2(255),
    "build_definition" CLOB, "owner_id" NUMBER(19)
  )`,
  `CREATE TABLE "dataset_fields" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "dataset_id" NUMBER(19) NOT NULL,
    "name" VARCHAR2(255) NOT NULL, "label" VARCHAR2(255) NOT NULL, "type" VARCHAR2(50) NOT NULL,
    "position" NUMBER(10) NOT NULL DEFAULT 0,
    CONSTRAINT fk_dataset_fields_dataset FOREIGN KEY ("dataset_id") REFERENCES "datasets"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE "charts" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR2(255) NOT NULL,
    "dataset_id" NUMBER(19) NOT NULL, "chart_type" VARCHAR2(50) NOT NULL, "config" CLOB NOT NULL,
    "owner_id" NUMBER(19), "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_charts_dataset FOREIGN KEY ("dataset_id") REFERENCES "datasets"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE "dashboards" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR2(255) NOT NULL,
    "layout" CLOB NOT NULL, "gap_x" NUMBER(10) NOT NULL DEFAULT 12, "gap_y" NUMBER(10) NOT NULL DEFAULT 12,
    "card_style" CLOB NOT NULL, "owner_id" NUMBER(19), "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP
  )`,
  `CREATE TABLE "users" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "email" VARCHAR2(255) NOT NULL,
    "password_hash" VARCHAR2(255) NOT NULL, "name" VARCHAR2(255) NOT NULL DEFAULT '',
    "is_active" NUMBER(1) NOT NULL DEFAULT 1, "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE ("email")
  )`,
  `CREATE TABLE "roles" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "code" VARCHAR2(50) NOT NULL,
    "name" VARCHAR2(255) NOT NULL, "description" VARCHAR2(500) NOT NULL DEFAULT '',
    "is_builtin" NUMBER(1) NOT NULL DEFAULT 0, "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_roles_code UNIQUE ("code")
  )`,
  `CREATE TABLE "permissions" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "code" VARCHAR2(100) NOT NULL,
    "name" VARCHAR2(255) NOT NULL, "description" VARCHAR2(500) NOT NULL DEFAULT '',
    CONSTRAINT uq_permissions_code UNIQUE ("code")
  )`,
  `CREATE TABLE "role_permissions" (
    "role_id" NUMBER(19) NOT NULL, "permission_id" NUMBER(19) NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY ("role_id", "permission_id"),
    CONSTRAINT fk_rp_role FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE,
    CONSTRAINT fk_rp_perm FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE "user_roles" (
    "user_id" NUMBER(19) NOT NULL, "role_id" NUMBER(19) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY ("user_id", "role_id"),
    CONSTRAINT fk_ur_user FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
    CONSTRAINT fk_ur_role FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE "refresh_tokens" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "user_id" NUMBER(19) NOT NULL,
    "token_hash" VARCHAR2(128) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "revoked_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_rt_user FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE "audit_logs" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "user_id" NUMBER(19), "email" VARCHAR2(255),
    "action" VARCHAR2(100) NOT NULL, "resource_type" VARCHAR2(50), "resource_id" VARCHAR2(255),
    "detail" CLOB, "ip" VARCHAR2(128), "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP
  )`,
  `CREATE TABLE "data_sources" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR2(255) NOT NULL,
    "type" VARCHAR2(50) NOT NULL, "config" CLOB NOT NULL, "is_active" NUMBER(1) NOT NULL DEFAULT 1,
    "owner_id" NUMBER(19), "mode" VARCHAR2(20) NOT NULL DEFAULT 'direct', "last_test_at" TIMESTAMP,
    "last_test_ok" NUMBER(1), "last_test_msg" VARCHAR2(2000), "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP
  )`,
  'CREATE INDEX idx_data_sources_owner ON "data_sources"("owner_id")',
  'CREATE INDEX idx_data_sources_type ON "data_sources"("type")',
  'CREATE INDEX idx_datasets_owner ON "datasets"("owner_id")',
  'CREATE INDEX idx_charts_owner ON "charts"("owner_id")',
  'CREATE INDEX idx_dashboards_owner ON "dashboards"("owner_id")',
  'CREATE INDEX idx_refresh_tokens_hash ON "refresh_tokens"("token_hash")',
  `CREATE TABLE "sync_configs" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "datasource_id" NUMBER(19) NOT NULL,
    "source_schema" VARCHAR2(255), "source_table" VARCHAR2(255) NOT NULL, "local_table" VARCHAR2(255) NOT NULL,
    "target_type" VARCHAR2(20) NOT NULL DEFAULT 'app', "strategy" VARCHAR2(20) NOT NULL DEFAULT 'incremental',
    "watermark_field" VARCHAR2(255), "watermark_kind" VARCHAR2(20) NOT NULL DEFAULT 'id', "primary_key" VARCHAR2(255),
    "sync_interval_seconds" NUMBER(10) NOT NULL DEFAULT 86400,
    "last_sync_at" TIMESTAMP, "last_watermark" VARCHAR2(255), "last_sync_status" VARCHAR2(20), "last_sync_msg" VARCHAR2(4000),
    "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_sync_configs UNIQUE ("datasource_id", "source_schema", "source_table"),
    CONSTRAINT fk_sync_configs_ds FOREIGN KEY ("datasource_id") REFERENCES "data_sources"("id") ON DELETE CASCADE
  )`,
  `CREATE TABLE "sync_logs" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "sync_config_id" NUMBER(19) NOT NULL,
    "started_at" TIMESTAMP, "finished_at" TIMESTAMP, "status" VARCHAR2(20), "rows_synced" NUMBER(10), "message" VARCHAR2(4000),
    CONSTRAINT fk_sync_logs_cfg FOREIGN KEY ("sync_config_id") REFERENCES "sync_configs"("id") ON DELETE CASCADE
  )`,
  'CREATE INDEX idx_sync_configs_ds ON "sync_configs"("datasource_id")',
  `CREATE TABLE "sync_locks" (
    "lock_name" VARCHAR2(128) NOT NULL PRIMARY KEY, "locked_by" VARCHAR2(64),
    "locked_until" NUMBER(20) NOT NULL DEFAULT 0,
    "updated_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP
  )`,
  `CREATE TABLE "dashboard_shares" (
    "id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "dashboard_id" NUMBER(19) NOT NULL,
    "token" VARCHAR2(64) NOT NULL, "password_hash" VARCHAR2(255) NOT NULL,
    "expires_at" TIMESTAMP, "is_active" NUMBER(1) NOT NULL DEFAULT 1, "created_by" NUMBER(19) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_dashboard_shares_token UNIQUE ("token"),
    CONSTRAINT fk_dashboard_shares_dash FOREIGN KEY ("dashboard_id") REFERENCES "dashboards"("id") ON DELETE CASCADE
  )`,
  'CREATE INDEX idx_dashboard_shares_dashboard ON "dashboard_shares"("dashboard_id")',
];